version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      uptrace/bun:
        applies-to: version-updates
        patterns:
          - "github.com/uptrace/bun"
          - "github.com/uptrace/bun/*"
          - "github.com/a-novel-kit/context/pgbun"
  - package-ecosystem: "github-actions"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
