sender:
  name: Agora des Écrivains
  email: noreply@agoradesecrivains.com
  password: ${SMTP_PASSWORD}
  domain: smtp-relay.gmail.com
addr: smtp-relay.gmail.com:587
urls:
  updateEmail: ${AUTH_PLATFORM_URL_UPDATE_EMAIL}
  updatePassword: ${AUTH_PLATFORM_URL_UPDATE_PASSWORD}
  register: ${AUTH_PLATFORM_URL_REGISTER}
