name: clean
on: [ delete ]

jobs:
  delete-api-container:
    if: github.event.ref_type == 'branch'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: a-novel-kit/workflows/.github/workflows/clean-containers.yaml@master
    with:
      app: api/staging

  delete-rotate-keys-container:
    if: github.event.ref_type == 'branch'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: a-novel-kit/workflows/.github/workflows/clean-containers.yaml@master
    with:
      app: rotate_keys/staging
